[[dependencies]]
  name = "github.com/davecgh/go-spew"
  version = "^1.1.0"

[[dependencies]]
  name = "github.com/pmezard/go-difflib"
  version = "^1.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/stretchr/testify"
